### ISSUE TITLE
右上方的文档图标不能中键点开小窗

### ISSUE THREAD

**Issue by Achuan-2** [frostime/sy-midclick-window#1]
很棒的插件，之前就觉得思源打开小窗太麻烦了
不过发现右上方文档图标不能中键点开小窗，如果支持的话，就可以更快捷把文档也用小窗打开了
![Clip_2024-07-18_09-54-56](https://github.com/user-attachments/assets/486404f5-d9ca-49dd-9337-525bb68607d2)

**Comment by frostime** [comment]
插件是通过判断 `data-id` 属性来决定哪个元素可以打开小窗的，这个按钮上面没有这个属性。

不过我可以额外做特殊处理。

![image](https://github.com/user-attachments/assets/23d7fe1c-62c0-42a0-9480-e8590931fe5d)

**Comment by Achuan-2** [comment]
辛苦大佬咯！
